### ISSUE TITLE
Upgrade System.Net.Sockets, Version=4.1 to 4.3

### ISSUE THREAD

**Issue by Toby-Broom** [chausner/BoincRpc#1]
I tried to build this with VS.Net 2017 but seems to use 4.1 when I have 4.3 on my computer so will not run as it can not find the 4.1 files.

**Comment by chausner** [comment]
I can reproduce the issue. The problem occurs when referencing BoincRpc (which is a .NET Standard library) from a normal .NET Framework project. I am fairly certain that this is supposed to be supported but it looks like the tooling is not ready yet. An easy workaround is to edit BoincRpc.csproj and set the target framework to "net46":
```xml
<TargetFramework>net46</TargetFramework>
```
You should then be able to reference the library from a .NET 4.6 project.

**Comment by Toby-Broom** [comment]
This work around fixes it for me, for a libary it uses .net standard 1.x by default.  My workaround was to use nget and get all the dlls in the folders with yours not much fun.  Thanks
