### ISSUE TITLE
Rename Close() to Disconnect()

### ISSUE THREAD

**Issue by adamradocz** [chausner/BoincRpc#8]
The `RpcClient` class has a `Connect` method, and the opposite of that is `Disconnect`, so it would be a more appropriate naming instead of the `Close`.

We could simply rename the `Close`, or we could create a new method named `Disconnect` and redirect the `Close` and mark it as deprecated.

**Comment by chausner** [comment]
Yes, I agree the naming is not ideal. I intended it to be consistent with `TcpClient.Close` but you may argue that `TcpClient.Close` also marks the instance as disposed while `RpcClient.Close` only closes the connection and allows reconnects afterwards. So `RpcClient.Close` is actually more similar to `Socket.Disconnect(true)`.

Still, I'd like to avoid breaking changes when possible so I would just leave it as it is.
